# This example demonstrates the ability for a workflow to create a 
# temporary, ephemeral volume used by the workflow, and delete it
# when the workflow completes. It uses the same volumeClaimTemplates
# syntax as statefulsets.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: volumes-pvc-
spec:
  entrypoint: volumes-pvc-example
  volumeClaimTemplates:
  - metadata:
      name: outputdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: volumes-pvc-example
    steps:
    - - name: download
        template: hibiki-recorder
    - - name: print
        template: print-message

  - name: hibiki-recorder
    container:
      image: evoltaro/rec_hibiki:latest
      command: [ruby]
      args: [rec_hibiki.rb, llss]
      volumeMounts:
      - name: outputdir
        mountPath: /output

  - name: print-message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo getting message from volume; find /mnt/vol"]
      volumeMounts:
      - name: outputdir
        mountPath: /mnt/vol
